# render.yaml

services:
  # The Backend Service (Spring Boot)
  - type: web
    name: legal-backend
    runtime: docker
    repo: https://github.com/wrwoj/demo4
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 8080

  # The Frontend Service (React + Nginx)
  - type: web
    name: legal-frontend
    runtime: docker
    repo: https://github.com/wrwoj/demo4
    dockerfilePath: ./frontend/Dockerfile
    # Note: Set NGINX_BACKEND_URL environment variable manually in Render dashboard
    # Value should be: https://demo-dd7m.onrender.com (or your actual backend URL)