# render.yaml

services:
  # The Backend Service (Spring Boot)
  - type: pserv
    name: legal-backend
    runtime: docker
    repo: https://github.com/wrwoj/demo
    dockerfilePath: ./legal-advice-backend/Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 8080

  # The Frontend Service (React + Nginx)
  - type: web
    name: legal-frontend
    runtime: docker
    repo: https://github.com/wrwoj/demo
    dockerfilePath: ./legal-advice-frontend/Dockerfile
    envVars:
      # We now pass the host and port of the backend service separately
      - key: NGINX_BACKEND_HOST
        fromService:
          type: pserv
          name: legal-backend
          property: host # Get the internal host name
      - key: NGINX_BACKEND_PORT
        fromService:
          type: pserv
          name: legal-backend
          property: port # Get the internal port