# render.yaml

services:
  # The Backend Service (Spring Boot)
  - type: web
    name: legal-backend
    runtime: docker
    repo: https://github.com/wrwoj/demo4
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 8080

  # The Frontend Service (React + Nginx)
  - type: web
    name: legal-frontend
    runtime: docker
    repo: https://github.com/wrwoj/demo4
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      # Set the backend URL for nginx proxy
      - key: NGINX_BACKEND_URL
        fromService:
          type: web
          name: legal-backend
          property: url # Get the full URL of the backend service